### PR TITLE
Create MANIFEST.in and include requirement.txt

### PR DESCRIPTION
**Pull request by thewchan**
### What's Changed

Include `requirement.txt` in sdist but referring it in `MANIFEST.in`.

### Technical Description

Any specific technical detail that may provide additional context to aid code review.

> Before opening a Pull Request you should read and agreed to the Contributor Code of Conduct (see `CONTRIBUTING.md`\)

### CODE REVIEW

**Comment by apoclyps** [comment]
@thewchan can you please populate the pull request description for this change?

**Comment by apoclyps** [comment]
I'll take a look the next day to check what should be included in the  `MANIFEST.in`. Feel free to include these changes in your pull request if you already have any idea of what is missing.

At a glance, https://github.com/mgedmin/check-manifest looks like it could be useful for checking this in future - especially the pre-commit hook. 

As for what is missing, the [long description](https://github.com/apoclyps/reviews/blob/main/setup.py#L9-L10) comes from the readme so it looks like it will need to be included


> https://packaging.python.org/en/latest/guides/using-manifest-in/
>
> There may even be extra files that you need to include; for example, if your setup.py computes your project’s long_description by reading from both a README and a changelog file, you’ll need to include both those files in the sdist so that people that build or install from the sdist get the correct results.

**Comment by thewchan** [comment]
@apoclyps this is actually a very simple PR, nothing is changed except now `requirements.txt` will also be included in the source code sdist on PyPI. You can check here: https://packaging.python.org/en/latest/guides/using-manifest-in/ to see the default files included, and if you want to include/exclude certain files from the sdist.

**Review by apoclyps — APPROVED** [review]

**Comment by thewchan** [comment]
@apoclyps thanks so much, if it's possible please let me know when a new release is pushed to PyPI that includes this? My plan is to try putting this package on conda forge for broader exposure

**Comment by apoclyps** [comment]
awesome @thewchan; do let me know how that goes 👍 

I've released `0.4.1` with this change on PyPi: https://pypi.org/project/reviews

**Pull request merged**
