### PR TITLE
Fixes #181 (WIP)

### LINKED ISSUE #181: [Feature] Add flag to dashboard to hide/show authors pull requests
**Is your feature request related to a problem? Please describe.**
When reviewing pull requests, occasionally I only need to see the pull requests of others to review their code, or pull requests of my own to ship a pull request that is ready.

**Describe the solution you'd like**
Whilst watching repositories in which I have contributed pull requests, I would like to filter the results to hide all pull requests authored by github user or display only the pull requests authored by my gitub user. 

**Additional context**
* flags provided to the render functions to show/hide pull requests from the author will need to be included in both render functions: https://github.com/apoclyps/reviews/blob/main/reviews/commands.py#L45-L70

### PR DESCRIPTION
**Pull request by paulosgf**
- Added PR Github Author column to the dashboard.

### What's Changed

A description of the issue/feature; reference the issue number (if one exists). The Pull Request should not include fixes for issues other than the main issue/feature request.

### Technical Description

Any specific technical detail that may provide additional context to aid code review.

> Before opening a Pull Request you should read and agreed to the Contributor Code of Conduct (see `CONTRIBUTING.md`\)

### CODE REVIEW

**Comment by paulosgf** [comment]
Hi @apoclyps!

I'm making a new push with some changes.
To implement this enhancement with GitLab, I modified the following files:

On code_review_requests tuple of `GitlabPullRequestController` class, i added the entry `user=pull_request.author['username']`

```
reviews/controller.py
class GitlabPullRequestController():

code_review_requests.append(
                PullRequest(
                  user=pull_request.author['username'],
```

This entry is referenced by both classes `GitlabPullRequestController` and `GithubPullRequestController`, and is called in a row on method `render_pull_request_table()`
```
reviews/layout/helpers.py
  def render_pull_request_table(
            row = [
            f"[white]{pr.number} ",
            pr.render_title(),
            f"[white]{pr.user} ",
            pr.render_labels(label_colour_map),
        ]
```

To get pull requests from `GitlabPullRequestController` class it's needed to exchange` list()` by the` get() `method and pass the project ID as function's argument.
```
reviews/source_control/client.py
class GitlabAPI:

 def get_pull_requests(self, project_id: str, namespace: str) -> List[GitlabMergeRequest]:
  return repository.mergerequests.get(id=project_id, state="opened", order_by="created_at", sort="asc")
```

But, contrary to what happens with the `code_review_requests() `method of `GithubPullRequestController` class, on `GitlabPullRequestController` class it doesn't find any pull request and returns this error:
```
File "/home/paulo/PycharmProjects/reviews/venv/lib/python3.8/site-packages/gitlab/client.py", line 727, in http_request
    raise gitlab.exceptions.GitlabHttpError(
  gitlab.exceptions.GitlabHttpError: 404: 404 Not found
```

I have debugged a while and find that on `~/.local/lib/python3.8/site-packages/gitlab/mixins:111` the `query_data = {} `variable is empty when is made GET request to the Gitlab server:
```
def http_get(query_data: Optional[Dict[str, Any]] = None,
"""Make a GET request to the Gitlab server
Args:
               path: Path or full URL to query ('/projects' or 'http://whatever/v4/api/projecs')                          
               query_data: Data to send as query parameters
```

Then, thereafter, I didn't make any progress anymore. Could you give some help?

**Comment by apoclyps** [comment]
@paulosgf sure, I'll try and set some time aside after work this evening to review this pull request and provide assistance on where to go next and how to proceed 👍

**Comment by apoclyps** [comment]
@paulosgf thank you for the detailed comment; I've contracted covid-19 last week so it's taken me slightly longer to return to looking into/reviewing this pull request.

After spending some time looking into the issue with Gitlab, it appears to be a change related to a `MergeRequest` and a `ProjectMergeRequest`; you can see the changes I made in the third pull request to resolve this change. 

As for the configuration for `show/hide author` - I made this an ENV var to avoid passing it through multiple functions/classes from the CLI. Overall `reviews` is in need of an extensive refactor - I'm currently looking into building a new self-hosted web-based version to replace the CLI. 

* [refactors user to author] in (https://github.com/apoclyps/reviews/pull/382/commits/5e4f8e13588b577a8d012066c3fab3be5d8d4711)
* [adds configuration to show/hide author] in (https://github.com/apoclyps/reviews/pull/382/commits/026864b4090305f49f0cd67544974b0ae365ed9f)
* [updates gitlab to handle changes to their API] in https://github.com/apoclyps/reviews/pull/382/commits/280630fbd72d58de939d51e1a2296ebb84b43933)

**Comment by apoclyps** [comment]
**Screenshots**

```bash
python -m reviews dashboard --no-reload --provider=github
```

image

```bash
export REVIEWS_AUTHOR=false
python -m reviews dashboard --no-reload --provider=github
```

image

**Review by apoclyps — APPROVED** [review]

**Comment by paulosgf** [comment]
@apoclyps I'm so glad that you're good now! It must be a terrible experience in all aspects... but unfortunately, all of us are subject to this. 
I would like to thank you for your help with this. It was a great experience and I learned a lot from it!
Count with me, within my possibilities, for help on refactoring to a web-based version. Maybe Django? It's my next step in learning. 
Embraces!

**Comment by paulosgf** [comment]
@apoclyps I'm so glad that you're good now! It must be a terrible experience in all aspects... but unfortunately, all of us are subject to this. 
I would like to thank you for your help with this. It was a great experience and I learned a lot from it!
Count with me, within my possibilities, for help on refactoring to a web-based version. Maybe Django? It's my next step in learning. 
Embraces!

**Comment by apoclyps** [comment]
I've currently been considering FastAPI and celery as it seems like a good opportunity to try out some new tech. I'm certain that Django is more than capable as I've used it for several projects in the past however I'm curious to see how minimalist I can build it - in order to help others easily onboard and extend the solution.

**Pull request merged**
